import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CmSidebar from './Sidebar' // header 컴포넌트

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Taeil's Playground`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CmSidebar contents={children}></CmSidebar>
      </body>
    </html>
  )
}
